title: Noor Tutoring
description: "Noor Tutoring Website"
url: "moojid.github.io"          # set to https://noortutoring.com when deploying
baseurl: "/noortutoring.com"      # keep empty if served at domain root
timezone: America/Phoenix
permalink: /:categories/:title/
markdown: kramdown
theme: null
defaults:
  - scope: {path: "", type: "pages"}
    values: {layout: default}
  - scope: {path: "", type: "posts"}
    values: {layout: post}