title: Noor Tutoring
description: "Noor Tutoring Website"
url: "https://noortutoring.com"          # set to https://noortutoring.com when deploying
baseurl: ""      # keep empty if served at domain root #/noortutoring.com
timezone: America/Phoenix
permalink: /:categories/:title/
markdown: kramdown
theme: null
defaults:
  - scope: {path: "", type: "pages"}
    values: {layout: default}
  - scope: {path: "", type: "posts"}
    values: {layout: post}